controller_manager:
  ros_parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros_parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_name: ['left_wheel_joint']
    right_wheel_name: ['right_wheel_joint']
    wheel_seperation: 0.35
    wheel_radius: 0.05

    use_stamped_vel: false

    #open_loop: false

    #wheels_per_side: x
    wheel_separate_multiplier: x
    left_wheel_radius_multiplier: x
    right_wheel_radius_multiplier: x

    odem_frame_id: x
    pose_covariance_diagonal: x
    twist_covariance_diagnol: x
    open_loop: x
    enable_odom_tf: x

    cmd_vel_timeout: x
    publish_limited_velocity: x
    velocity_rolling_window_size: x

    linear.x.has_velocity_limits: false
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: NAN
    linear.x.min_velocity: NAN
    linear.x.max_acceleration: NAN
    linear.x.min_acceleration: NAN
    linear.x.max_jerk: NAN
    linear.X.min_jerk: NAN

    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: NAN
    angular.Z.min_velocity: NAN
    angular.z.max_acceleration: NAN
    angular.z.min_acceleration: NAN
    angular.z.max_jerk: NAN
    angular.z.min_jerk: NAN

joint_broad:
  ros_parameters:
